spring:
  application:
    name: Nexio

  # Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nexio_db?useSSL=false
    username: postgres
    password: 1234

  # JPA properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 95828313160-fuu5ar2cgkkehbgde67dnc8edqgc6dk9.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Ov23li53W0tk7iZjpAUP
            client-secret: 0c9aacca7cdd7d6e326e0cb626f495840d5d527d



# User properties
users:
  defaultUser:
    userRole: USER
    activeByDefault: true

# Logging Levels
logging:
  level:
    # Disable the default loggers
    org: WARN
    blog: WARN
    # Show SQL executed with parameter bindings
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor: TRACE